# Exercícios Pandas

#### 1)  crie uma série do pandas a partir de uma lista com os dados abaixo:

Em um estudo sobre alteração na tempreatura global, A NASA disponibiliza dados de diferenças de temperatura média da superfície terrestre relativos às médias de temperatura entre 1951 e 1980. Os dados originais podem ser vistos no site da NASA/GISS, e estão dispostos a cada década na tabela abaixo.

|ano|anomalia térmica|
|:-:|:----:|
| 1900 | -0.08 |
| 1920 | -0.27 |
| 1940 | 0.12 |
| 1960 | -0.03 |
| 1980 | 0.26 |
| 2000 | 0.40 |
| 2020 | 1.02 |

Crie uma séries do Pandas a partir de uma lista com esses dados.

In [1]:
import pandas as pd
import numpy as np

# Seu código aqui
temperatura = pd.Series([-.08, -.27, .12, -.03, .26, .40, 1.02])
temperatura

0   -0.08
1   -0.27
2    0.12
3   -0.03
4    0.26
5    0.40
6    1.02
dtype: float64

#### 2) Coloque os anos nos índices conforme a tabela.

In [2]:
# seu código aqui
temperatura = pd.Series([-.08, -.27, .12, -.03, .26, .40, 1.02],
                        index= [1900, 1920, 1940, 1960, 1980, 2000, 2020])
temperatura

1900   -0.08
1920   -0.27
1940    0.12
1960   -0.03
1980    0.26
2000    0.40
2020    1.02
dtype: float64

#### 3) A partir do dicionário abaixo, crie uma séries do Pandas:

In [37]:
from ast import Name
from os import rename
dic_temperaturas = {1900: -.08, 1920: -.27, 1940: .12, 1960: -.03, 1980: .26, 2000: .40, 2020: 1.02}
dic_temp = {
    'Ano': [1900, 1920, 1940, 1960, 1980, 2000, 2020],
    'Temperatura' : [-.08, -.27, .12, -.03, .26, .40, 1.02]
}

# seu código aqui
df = pd.Series(dic_temperaturas)
#df.columns = ['Ano', 'Temperatura']
#df = pd.DataFrame(dic_temp)
df

1900   -0.08
1920   -0.27
1940    0.12
1960   -0.03
1980    0.26
2000    0.40
2020    1.02
dtype: float64

#### 4) Transforme o ndarray abaixo em um dataframe.
O numpy é capaz de gerar arrays n-dimensionais com números pseudo-aleatórios de acordo com uma variedade de distribuições, como no exemplo abaixo. Transforme esse nd-array em um DataFrame.

In [29]:
arr = np.random.normal(100, 10, (20,3))

# seu código aqui
df = pd.DataFrame(arr)
df

             0           1           2
0   107.874571  100.676511   90.116816
1   104.262285  101.680690  112.760879
2   100.569201  108.874706  106.271832
3    85.274293   76.196189  118.941376
4   107.204192   82.959344  103.324151
5   110.047504   92.789989  108.826166
6    93.562626   96.737744   81.794656
7    99.780079  116.505514   95.407167
8    98.106346   85.313861  102.856234
9    86.852600  104.209842   81.017639
10  116.318868  102.878912  106.795963
11  100.424290  108.671823  111.001912
12  103.842683   90.374661   91.286506
13   96.428048   96.590094  100.435683
14  112.957894  110.650943  104.216561
15  112.138274  100.283410   95.707383
16  103.877572  101.774043  124.564997
17   92.095420   96.423385  100.933413
18   94.271824   99.766141  101.686296
19   90.576378  105.142712  106.094820

#### 5) Nomeie os índices das linhas com inteiros de 1 a 20, e as colunas com os nomes "x1", "x2", e "x3" respectivamente.

In [31]:
#seu código aqui
df.columns = ['x1', 'x2', 'x3']
df.index = range(1, 21)
df

            x1          x2          x3
1   107.874571  100.676511   90.116816
2   104.262285  101.680690  112.760879
3   100.569201  108.874706  106.271832
4    85.274293   76.196189  118.941376
5   107.204192   82.959344  103.324151
6   110.047504   92.789989  108.826166
7    93.562626   96.737744   81.794656
8    99.780079  116.505514   95.407167
9    98.106346   85.313861  102.856234
10   86.852600  104.209842   81.017639
11  116.318868  102.878912  106.795963
12  100.424290  108.671823  111.001912
13  103.842683   90.374661   91.286506
14   96.428048   96.590094  100.435683
15  112.957894  110.650943  104.216561
16  112.138274  100.283410   95.707383
17  103.877572  101.774043  124.564997
18   92.095420   96.423385  100.933413
19   94.271824   99.766141  101.686296
20   90.576378  105.142712  106.094820

#### 6) No DataFrame do exercício 5, crie uma nova coluna como sendo a média das três colunas, e dê a ela o nome de "media" (não recomendo colocar acentos em nomes de variáveis).

In [14]:
# seu código aqui
df["Media"] = df.mean(axis=1)
df

            x1          x2          x3       Media
0    89.415993   83.981463  104.038724   92.478726
1   115.152098  101.778275  113.271836  110.067403
2   113.845816   90.582752  100.138350  101.522306
3   109.162702   88.564776   79.910858   92.546112
4    99.834927  114.786625   94.858861  103.160137
5   110.411662   91.322591  102.480367  101.404873
6    92.653773   95.331079  103.138911   97.041254
7    95.047297  126.930578  109.337784  110.438553
8    93.780933  105.696647  104.799126  101.425569
9   113.309592  102.693402   93.855796  103.286263
10  108.517617   99.248292   82.135898   96.633936
11  119.335363   94.334285   90.496739  101.388796
12  103.330917  110.770327  101.578400  105.226548
13   89.702528   96.285787  104.075681   96.687999
14   92.048475  110.320065  104.122608  102.163716
15   94.694574   93.671260  103.324174   97.230003
16   80.781481   96.518091  106.240043   94.513205
17   94.969084  104.272683   98.969528   99.403765
18  106.354255  114.678907   87.192220  102.741794
19   89.492274  115.778803   82.885357   96.052144

#### 7) No DataFrame do exercício 6, crie uma nova coluna chamada "log_med", contendo o logaritmo natural da média calculada no exercício 6 <br>

In [16]:
# seu código aqui
df["log_med"] = np.log(df["Media"])
df

            x1          x2          x3       Media   log_med
0    89.415993   83.981463  104.038724   92.478726  4.526979
1   115.152098  101.778275  113.271836  110.067403  4.701093
2   113.845816   90.582752  100.138350  101.522306  4.620279
3   109.162702   88.564776   79.910858   92.546112  4.527707
4    99.834927  114.786625   94.858861  103.160137  4.636283
5   110.411662   91.322591  102.480367  101.404873  4.619121
6    92.653773   95.331079  103.138911   97.041254  4.575136
7    95.047297  126.930578  109.337784  110.438553  4.704459
8    93.780933  105.696647  104.799126  101.425569  4.619325
9   113.309592  102.693402   93.855796  103.286263  4.637504
10  108.517617   99.248292   82.135898   96.633936  4.570930
11  119.335363   94.334285   90.496739  101.388796  4.618963
12  103.330917  110.770327  101.578400  105.226548  4.656116
13   89.702528   96.285787  104.075681   96.687999  4.571489
14   92.048475  110.320065  104.122608  102.163716  4.626577
15   94.694574   93.671260  103.324174   97.230003  4.577079
16   80.781481   96.518091  106.240043   94.513205  4.548740
17   94.969084  104.272683   98.969528   99.403765  4.599190
18  106.354255  114.678907   87.192220  102.741794  4.632219
19   89.492274  115.778803   82.885357   96.052144  4.564891

#### 8) Análise de Vendas de Jogos Eletrônicos com Pandas

1. Baixe o dataset **"Venda de jogos"** (Video Game Sales), que contém dados sobre jogos com mais de 100.000 cópias vendidas.

- Baixe a base: [Clique aqui para baixar o arquivo](https://drive.google.com/file/d/1LTQSnw4ft90OCA7k2OwPw71MGY52FrSI/view?usp=sharing)

A fonte original é o site [vgchartz.com](https://www.vgchartz.com).

2. Carregue os dados usando a biblioteca `pandas`.
3. Responda às perguntas abaixo com base na sua análise.

#### Dicionário de Dados - Venda de Jogos

Este dicionário descreve cada uma das colunas presentes no dataset de vendas de jogos eletrônicos.

| Coluna         | Tipo de Dado     | Descrição                                                                 |
|----------------|------------------|---------------------------------------------------------------------------|
| `Rank`         | Inteiro          | Posição no ranking geral de vendas globais.                              |
| `Name`         | Texto (string)   | Nome do jogo.                                                             |
| `Platform`     | Texto (string)   | Plataforma em que o jogo foi lançado (ex: PS4, PC, Xbox One, etc.).      |
| `Year`         | Numérico (float) | Ano de lançamento do jogo.                                               |
| `Genre`        | Texto (string)   | Gênero do jogo (ex: Action, Sports, RPG, etc.).                          |
| `Publisher`    | Texto (string)   | Empresa responsável pela publicação do jogo.                             |
| `NA_Sales`     | Numérico (float) | Vendas na América do Norte (em milhões de unidades).                     |
| `EU_Sales`     | Numérico (float) | Vendas na Europa (em milhões de unidades).                               |
| `JP_Sales`     | Numérico (float) | Vendas no Japão (em milhões de unidades).                                |
| `Other_Sales`  | Numérico (float) | Vendas no restante do mundo (exceto NA, EU e JP), em milhões de unidades.|
| `Global_Sales` | Numérico (float) | Total de vendas globais (em milhões de unidades).                        |


---

## Perguntas

1. **Qual foi o gênero de jogo com o maior volume de vendas globais (`Global_Sales`)?**  
   *Dica:* Use `groupby` com a coluna `Genre` e some as vendas globais.

2. **Quais são as 5 plataformas com maior média de vendas na América do Norte (`NA_Sales`)?**  
   *Dica:* Use `groupby` na coluna `Platform` e calcule a média de `NA_Sales`.

3. **Qual publisher lançou o maior número de jogos entre os anos de 2000 e 2010?**  
   *Dica:* Filtre as linhas com `Year` entre 2000 e 2010 e conte os jogos por `Publisher`.

4. **Existe alguma relação aparente entre as vendas no Japão (`JP_Sales`) e o gênero do jogo?**  
   *Dica:* Compare as médias ou medianas de `JP_Sales` por `Genre` e descreva o que observou.

---

In [39]:
import pandas as pd
import numpy as np
import math

# Montando o Drive
from google.colab import drive
drive.mount('/content/drive')

# Caminho do diretório escolhido
path = "/content/drive/MyDrive/DataScience"

# Leitura do arquivo
df = pd.read_csv(path + '/vgsales.csv', sep=',')

# Mostrando as 10 primeiras linhas
df.head(10)

Mounted at /content/drive

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31

In [44]:
dist_maior_venda = pd.DataFrame({'Genre': df.Genre, 'Global_sales': df.Global_Sales})

ValueError: Length mismatch: Expected axis has 16598 elements, new values have 19 elements